import { Company } from "@/types/company";

export const availableCompanies: Company[] = [
  // ---- Original tickers ----
  {
    id: "nvda",
    name: "NVIDIA Corporation",
    ticker: "NVDA",
    sector: "Semiconductors",
    marketCap: "$3.3T",
    historicalNewsAvailable: true,
    etfSubSector: "Semiconductors & Hardware",
    isMoatEtfHolding: true,
  },
  {
    id: "aapl",
    name: "Apple Inc.",
    ticker: "AAPL",
    sector: "Technology",
    marketCap: "$3.7T",
    historicalNewsAvailable: true,
  },
  {
    id: "msft",
    name: "Microsoft Corporation",
    ticker: "MSFT",
    sector: "Technology",
    marketCap: "$3.1T",
    historicalNewsAvailable: true,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },
  {
    id: "avgo",
    name: "Broadcom Inc.",
    ticker: "AVGO",
    sector: "Semiconductors",
    marketCap: "$790B",
    historicalNewsAvailable: true,
    etfSubSector: "Semiconductors & Hardware",
    isMoatEtfHolding: true,
  },
  {
    id: "orcl",
    name: "Oracle Corporation",
    ticker: "ORCL",
    sector: "Software",
    marketCap: "$530B",
    historicalNewsAvailable: true,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },
  {
    id: "amd",
    name: "Advanced Micro Devices",
    ticker: "AMD",
    sector: "Semiconductors",
    marketCap: "$210B",
    historicalNewsAvailable: true,
  },
  {
    id: "csco",
    name: "Cisco Systems",
    ticker: "CSCO",
    sector: "Networking",
    marketCap: "$240B",
    historicalNewsAvailable: true,
  },
  {
    id: "pltr",
    name: "Palantir Technologies",
    ticker: "PLTR",
    sector: "Software & AI",
    marketCap: "$180B",
    historicalNewsAvailable: false,
  },
  {
    id: "mu",
    name: "Micron Technology",
    ticker: "MU",
    sector: "Memory & Storage",
    marketCap: "$110B",
    historicalNewsAvailable: true,
  },
  {
    id: "googl",
    name: "Alphabet Inc.",
    ticker: "GOOGL",
    sector: "Technology",
    marketCap: "$2.0T",
    historicalNewsAvailable: true,
  },

  // ---- MOAT ETF: Software & SaaS ----
  {
    id: "adbe",
    name: "Adobe Inc.",
    ticker: "ADBE",
    sector: "Software",
    marketCap: "$180B",
    historicalNewsAvailable: true,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },
  {
    id: "crm",
    name: "Salesforce.com Inc.",
    ticker: "CRM",
    sector: "Software",
    marketCap: "$270B",
    historicalNewsAvailable: false,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },
  {
    id: "now",
    name: "ServiceNow Inc.",
    ticker: "NOW",
    sector: "Software",
    marketCap: "$190B",
    historicalNewsAvailable: false,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },
  {
    id: "wday",
    name: "Workday Inc.",
    ticker: "WDAY",
    sector: "Software",
    marketCap: "$65B",
    historicalNewsAvailable: true,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },
  {
    id: "veev",
    name: "Veeva Systems Inc.",
    ticker: "VEEV",
    sector: "Software",
    marketCap: "$35B",
    historicalNewsAvailable: false,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },
  {
    id: "ddog",
    name: "Datadog Inc.",
    ticker: "DDOG",
    sector: "Software",
    marketCap: "$40B",
    historicalNewsAvailable: true,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },
  {
    id: "tyl",
    name: "Tyler Technologies Inc.",
    ticker: "TYL",
    sector: "Software",
    marketCap: "$23B",
    historicalNewsAvailable: false,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },
  {
    id: "fico",
    name: "Fair Isaac Corp.",
    ticker: "FICO",
    sector: "Software",
    marketCap: "$45B",
    historicalNewsAvailable: false,
    etfSubSector: "Software & SaaS",
    isMoatEtfHolding: true,
  },

  // ---- MOAT ETF: Semiconductors & Hardware ----
  {
    id: "nxpi",
    name: "NXP Semiconductors NV",
    ticker: "NXPI",
    sector: "Semiconductors",
    marketCap: "$55B",
    historicalNewsAvailable: true,
    etfSubSector: "Semiconductors & Hardware",
    isMoatEtfHolding: true,
  },
  {
    id: "amat",
    name: "Applied Materials Inc.",
    ticker: "AMAT",
    sector: "Semiconductors",
    marketCap: "$140B",
    historicalNewsAvailable: true,
    etfSubSector: "Semiconductors & Hardware",
    isMoatEtfHolding: true,
  },
  {
    id: "entg",
    name: "Entegris Inc.",
    ticker: "ENTG",
    sector: "Semiconductors",
    marketCap: "$17B",
    historicalNewsAvailable: true,
    etfSubSector: "Semiconductors & Hardware",
    isMoatEtfHolding: true,
  },

  // ---- MOAT ETF: Cybersecurity ----
  {
    id: "ftnt",
    name: "Fortinet Inc.",
    ticker: "FTNT",
    sector: "Cybersecurity",
    marketCap: "$75B",
    historicalNewsAvailable: true,
    etfSubSector: "Cybersecurity",
    isMoatEtfHolding: true,
  },
  {
    id: "panw",
    name: "Palo Alto Networks Inc.",
    ticker: "PANW",
    sector: "Cybersecurity",
    marketCap: "$120B",
    historicalNewsAvailable: true,
    etfSubSector: "Cybersecurity",
    isMoatEtfHolding: true,
  },

  // ---- MOAT ETF: Platforms & Data Infrastructure ----
  {
    id: "meta",
    name: "Meta Platforms Inc.",
    ticker: "META",
    sector: "Technology",
    marketCap: "$1.6T",
    historicalNewsAvailable: true,
    etfSubSector: "Platforms & Data Infrastructure",
    isMoatEtfHolding: true,
  },
  {
    id: "msi",
    name: "Motorola Solutions Inc.",
    ticker: "MSI",
    sector: "Communications",
    marketCap: "$75B",
    historicalNewsAvailable: false,
    etfSubSector: "Platforms & Data Infrastructure",
    isMoatEtfHolding: true,
  },
  {
    id: "br",
    name: "Broadridge Financial Solutions Inc.",
    ticker: "BR",
    sector: "Financial Technology",
    marketCap: "$25B",
    historicalNewsAvailable: false,
    etfSubSector: "Platforms & Data Infrastructure",
    isMoatEtfHolding: true,
  },
  {
    id: "tru",
    name: "TransUnion",
    ticker: "TRU",
    sector: "Data & Analytics",
    marketCap: "$15B",
    historicalNewsAvailable: false,
    etfSubSector: "Platforms & Data Infrastructure",
    isMoatEtfHolding: true,
  },
  {
    id: "csgp",
    name: "CoStar Group Inc.",
    ticker: "CSGP",
    sector: "Data & Analytics",
    marketCap: "$35B",
    historicalNewsAvailable: true,
    etfSubSector: "Platforms & Data Infrastructure",
    isMoatEtfHolding: true,
  },
];
