import { Company } from "@/types/company";

export const availableCompanies: Company[] = [
  {
    id: "nvda",
    name: "NVIDIA Corporation",
    ticker: "NVDA",
    sector: "Semiconductors",
    marketCap: "$3.3T",
    historicalNewsAvailable: true,
  },
  {
    id: "aapl",
    name: "Apple Inc.",
    ticker: "AAPL",
    sector: "Technology",
    marketCap: "$3.7T",
    historicalNewsAvailable: true,
  },
  {
    id: "msft",
    name: "Microsoft Corporation",
    ticker: "MSFT",
    sector: "Technology",
    marketCap: "$3.1T",
    historicalNewsAvailable: true,
  },
  {
    id: "avgo",
    name: "Broadcom Inc.",
    ticker: "AVGO",
    sector: "Semiconductors",
    marketCap: "$790B",
    historicalNewsAvailable: true,
  },
  {
    id: "orcl",
    name: "Oracle Corporation",
    ticker: "ORCL",
    sector: "Software",
    marketCap: "$530B",
    historicalNewsAvailable: true,
  },
  {
    id: "amd",
    name: "Advanced Micro Devices",
    ticker: "AMD",
    sector: "Semiconductors",
    marketCap: "$210B",
    historicalNewsAvailable: true,
  },
  {
    id: "csco",
    name: "Cisco Systems",
    ticker: "CSCO",
    sector: "Networking",
    marketCap: "$240B",
    historicalNewsAvailable: true,
  },
  {
    id: "pltr",
    name: "Palantir Technologies",
    ticker: "PLTR",
    sector: "Software & AI",
    marketCap: "$180B",
    historicalNewsAvailable: false, // IPO 2020, limited historical coverage
  },
  {
    id: "mu",
    name: "Micron Technology",
    ticker: "MU",
    sector: "Memory & Storage",
    marketCap: "$110B",
    historicalNewsAvailable: true,
  },
  {
    id: "googl",
    name: "Alphabet Inc.",
    ticker: "GOOGL",
    sector: "Technology",
    marketCap: "$2.0T",
    historicalNewsAvailable: true,
  },
];

